### ISSUE TITLE
numbering of entries

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#1]

**Comment by epicfaace** [comment]
proble

**Comment by quadrismegistus** [comment]
Re-upping this as Giovanna and I were talking about it.

Currently we have "Cobley" at number "1010.1" (http://grand-tour-explorer-2017.herokuapp.com/#/entries/1010.1).

However, "Cobley" is not related to "Harriet Cobley", who is number "1010". So far, we've been using decimals to indicate children, groups, etc. 

What do we do with these incorrectly indexed entries? Should we re-number all the entries? Or should we make "Cobley" number "1010.a" or something, to indicate that he is not a relation?

**Comment by epicfaace** [comment]
I would think re-numbering would be preferable.

**Comment by ceserani** [comment]
we will leave numbering as is, lest too much new confusion is introduced, but we should flag the few cases as the above one which resulted bc of parsing mixups--REMEMBER TO FLAG THESE?
