### ISSUE TITLE
other example of same problem in travel date search

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#100]
if you click in the Explorer on parma dates (right column under minimap) for Mary Berry (entry 392) you get to a list of everyone else who was there around those dates, which is the 13 travelers and the list in pic here below, but this list includes also Thomas Jones (entry 2715)who was in Parma in 1776, and Charles Parker (3728), Allan Ramsay (entry 4027) who was there in 1738, who was there in 1774, George Ashburnham (4200) who was there in 1783 but not in november, while if you serach in the Explorer for who was in Parma in 1783/11 you get 49 results. Why? What is the underlying rational for this search? What creates the Charles Parker mistake?

**Comment by ryanctan** [comment]
Looks fixed
