### ISSUE TITLE
travel dates bug

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#101]
once in an entry if you click on that person's trip to a location you are supposed to get everyone who was in that location at that time but it does not seem to work fully; example: for Mary (Hervey) Viscountess Erne, entry 1619, if you click on Florence 1786/1, you a number of people who were not there such as Mark Davis (entry 1323) who was in Florence in 1784 and 1785 not 1786. What might be the problem?

**Comment by epicfaace** [comment]
travel from 6/1785-5/1786 -- needs to match 1/1786

**Comment by epicfaace** [comment]
https://github.com/cestastanford/grandtour/blob/2192c1c5d072c4bfbd3059145bfe7a196fc4d9d9/query.js#L239

**Comment by epicfaace** [comment]
1786 - 173 (should be 337)
1786/1 - 35 (should be 53)
Florence - 2154
Florence + 1786/1 - 24

**Comment by epicfaace** [comment]
@mratan1 
need number of travelers who were in:
- Florence in 1768
- Florence
- 1/1768
- Florence 1/1768

**Comment by mratan1** [comment]
Number of unique travellers who went to florence:  2155
Number of unique travellers in 1786:  339
Number of unique travellers florence in 1786:  58

indexes of unique travellers florence in 1786
{'', 4358.0, 777.0, 395.0, 1164.0, 2445.0, 4117.0, 158.0, 2085.0, 2085.1, 4007.0, 1197.0, 686.0, 4909.1, 688.0, 688.1, 4909.2, 3266.0, 3266.1, 3266.2, 3013.0, 2758.0, 2758.1, 73.0, 587.0, 332.0, 332.1, 332.2, 332.3, 332.4, 1360.0, 2385.0, 1235.0, 1235.1, 1619.0, 3287.0, 4059.0, 3548.0, 3548.2, 3548.3, 5087.0, 3424.0, 3169.0, 3170.0, 3170.2, 3171.0, 2021.0, 2021.1, 2021.2, 2021.3, 4837.0, 5087.1, 2543.0, 4850.0, 3190.0, 250.0, 3325.0, 1279.0}

**Comment by mratan1** [comment]
Number of unique travellers who went to florence:  2154
Number of unique travellers in 1786:  338
Number of unique travellers florence in 1786:  57
Number of unique travellers 1/1786 58
Number of unique travellers in florence 1/1786 12

IDs of unique travellers in florence 1/1786
{'', 3424.0, 587.0, 332.2, 332.0, 332.1, 332.3, 1164.0, 1197.0, 2385.0, 1619.0, 2543.0, 158.0}

**Comment by epicfaace** [comment]
search 1/1788 - also get results for people in 1788
