### ISSUE TITLE
Add a "report an issue" button/dialog

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#103]

**Comment by ryanctan** [comment]
@epicfaace do you have any ideas for this? I can take it on if you like

**Comment by epicfaace** [comment]
- Perhaps we could use some library / tool like survey js (https://www.npmjs.com/package/survey-angular)? This comes with a way to manage responses.
- The other option is, maybe an easier way to do this is to just link to / embed a Google Form so we can handle responses and feedback that way.
- Finally, the last option is to implement everything ourselves; this would involve creating the frontend form and backend endpoints and database models to do so. This would probably be the most work and it's probably not the best way to do this.
