### ISSUE TITLE
Change the number that shows up

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#113]
The number should filter uniques by _all_ filters on the page (currently it only applies all other filters _but_ the filter of the current box).

![image](https://user-images.githubusercontent.com/1689183/58291401-1c891380-7d72-11e9-9a03-c8008622a65a.png)

**Comment by epicfaace** [comment]
Also, when in AND mode, do an AND query to get the numbers on the side.

When in OR mode, do an OR query to get the numbers on the side.

When some entries are already crossed out (negative), take the negative numbers into account when getting the numbers on the side.

**Comment by ryanctan** [comment]
@epicfaace is this issue fixed? If not, could you explain a bit about what the example should instead look like?

**Comment by epicfaace** [comment]
It's not fixed.

Look at the "DBITI Employments & Identifiers" box:
![image](https://user-images.githubusercontent.com/1689183/60556559-c99e6680-9cf6-11e9-9bfd-af0063285373.png)

When I select "painter", I expect all the numbers in the other rows "DBITI Employments & Identifiers" to change accordingly. This means that next to "merchant" should be the number of results that are both merchant AND painter, and so on.

Instead, the numbers don't change -- and you can see that the numbers in all the _other_ boxes are changing. The behavior we want is that the numbers in _all_ the boxes should change accordingly.
![image](https://user-images.githubusercontent.com/1689183/60556550-c1dec200-9cf6-11e9-8d61-84ccc3422176.png)
