### ISSUE TITLE
create a list in GTE based on a list of entries' numbers: winter break task

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#12]
The need for this came up in working with a scholar's data.
She had exported a set of data from the GTE (which is in the GTE a list), refined it out of the  GTE to get the set she wanted, and then we realized that to have this as a list in the GTE--which is desirable for a variety of research reasons--the only way would be to create it manually adding one entry after the other (no filtering would in this case recreate the result of the curation of the list done by the scholar). It would be great to have a way of having in the GTE the capability of creating a list out of a set of entries' numbers. Ashwin, can you think about how this would work? Do you have suggestions?

**Comment by epicfaace** [comment]
Button to add new list

**Comment by epicfaace** [comment]
done

![image](https://user-images.githubusercontent.com/1689183/51958703-127b8780-2406-11e9-9c9b-dc676f988719.png)

**Comment by ryanctan** [comment]
This was moved to Done
