### ISSUE TITLE
"( entries)" on search page placeholders

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#126]
Related to counts I believe. Especially affects the dates.

**Comment by epicfaace** [comment]
Code pointer -- this is where the counts are calculated: https://github.com/cestastanford/grandtour/blob/30667da2706ccd9a9905660c00ca756a5fbd8444/query.js#L19

We're missing counts for mentioned names, and the dates might not be being calculated correctly. Do you know which counts are working and which aren't?
