### ISSUE TITLE
Similar values in database either redundant or not consolidated

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#127]
May need to be done manually? Manifests in two ways:

1) Redundancy - some values are listed in multiple filters (dimensions), often with different counts, such as "physician" or "general". I've seen it in **Employments and Identifiers**, **Occupations and Posts**, and **Military Careers**. Are there ways we've defined these categories such that we can eliminate the inconsistent overlaps?

2) Lack of consolidation - some values should apparently combined. This is often a capitalization thing ("banker" is separate from "Banker") but other things are a result of the parsing. For example, "antiquary" and "antiquarian" are the same thing; every "landscape painter" should also be considered a "painter". Other cases are less clear-cut, such as whether it is desirable to consolidate "scientist", "man of science", and "natural philosopher", or consolidate every "amateur architect" into "architect".

**Comment by epicfaace** [comment]
Yeah, this might need to be done manually. You're right that consolidation is generally good, but at the same time the GTE wants to faithfully reproduce the data that was originally in the book as well. 

Manual work may take a long time and might not be worth it at this point. Thoughts @ceserani?

**Comment by ceserani** [comment]
As per our conversation, you picked up correctly that there are duplicate values in the database, but this has to do with our choice in transforming the print Dictionary into data; and the tooltip brief explanatory sentences and the language changes of the Explorer and the extensive text in the online book should make this clear, so let's keep an eye out that this will be the case as we go forward!
