### ISSUE TITLE
Birth place and death place not being exported

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#128]
Column names are there but no data is printed

**Comment by epicfaace** [comment]
Code pointer: https://github.com/cestastanford/grandtour/blob/779beaf60ea53add178114c90a7826bd532f0b6b/query.js#L564

Maybe you should check and see if d.dates[0].birthPlace actually contains the birth place.

**Comment by ryanctan** [comment]
Fixed by #139
