### ISSUE TITLE
Rename "pursuits" -> "employments and identifiers" in the filter part, everywhere

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#13]
Mainly in the filters

![image](https://user-images.githubusercontent.com/1689183/51076619-8d475300-164f-11e9-9ce0-29beb4d8c02a.png)

**Comment by epicfaace** [comment]
Fixed to say -- 
![image](https://user-images.githubusercontent.com/1689183/51076654-06df4100-1650-11e9-9a23-d4f62ae3793a.png)

**Comment by epicfaace** [comment]
Problem: doesn't look consistent though:

![image](https://user-images.githubusercontent.com/1689183/51076656-15c5f380-1650-11e9-80bc-41bba6c12ec1.png)

**Comment by ceserani** [comment]
I just noticed that in the data export the term pursuit is still current, when it shoudl be emplyments and identifiers

**Comment by ryanctan** [comment]
All discussed changes should be in the language-changes branch pull request
