### ISSUE TITLE
Saved lists count and exports do not include all selected entries

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#157]
<img width="1554" alt="Screen Shot 2019-07-25 at 5 07 50 AM" src="https://user-images.githubusercontent.com/51471027/61894253-e167a580-aec4-11e9-83c5-518d1fef430c.png">

<img width="1551" alt="Screen Shot 2019-07-25 at 5 08 14 AM" src="https://user-images.githubusercontent.com/51471027/61894270-ed536780-aec4-11e9-9796-ec4b9ca02ad1.png">

**Comment by ryanctan** [comment]
Fixes itself when page is updated...

**Comment by ryanctan** [comment]
@epicfaace any ideas for this? Because it fixes when the page is refreshed, I suspect it may have to do with async functions?

**Comment by epicfaace** [comment]
This is the code that renders the count -- https://github.com/cestastanford/grandtour/blob/df537c7afb0c13bf0b26dd6c490384a0ecafc98a/public/lists/lists.pug#L20 -- perhaps the issue is that list.entryIDs is not updating properly?
