### ISSUE TITLE
Entry number feature

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#172]
Some way to easily access entries by number, preferably multiple at a time. Perhaps in Search, Explore, or List.

We may also want Explore to have an option to browse all entries from the start.

**Comment by ceserani** [comment]
Possibly more like create a list out of submitted numbers
Maybe okay to have in Lists (now Saved Lists, maybe to be renamed YOUR LISTS) section as it is the kind of thing one lats to do only hen already familiar with working with lists

On Aug 16, 2019, at 4:56 PM, ryanctan <notifications@github.com<mailto:notifications@github.com>> wrote:


Some way to easily access entries by number, preferably multiple at a time. Perhaps in Search, Explore, or List.

We may also want Explore to have an option to browse all entries from the start.

**Comment by ryanctan** [comment]
Already implemented in List's import feature
