### ISSUE TITLE
about alpha

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#173]
ashwin and ryan, it will be great to have as soon as possible the current data uploaded onto the alpha site and no worries about erasing saved lists there (I just checked and they are of no consequences)
and the adding lists by entries IDs already exist and works on alpha! it presents as the option 'import' among the lists operations and i think this is just fine: it is a high level operation taht makes sense only after you have downloaded and worked with your own data so it should not be part of the explorer and search pages: great the way it is (maybe only tweaking language) and thanks for adding this earlier in the summer.
the only issue that again the number of entries in the list does not show correctly: see screenshot here below:
<img width="1281" alt="Screen Shot 2019-08-17 at 11 53 05 AM" src="https://user-images.githubusercontent.com/4521013/63216194-c1ec2300-c0e6-11e9-9281-cca41a0aeee0.png">

**Comment by ryanctan** [comment]
Ashwin has updated the data
