### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#178]
This is important and we need to have this before release.

**Comment by ceserani** [comment]
what's https?

**Comment by epicfaace** [comment]
If we don't have it, the site is "not secure".

![image](https://user-images.githubusercontent.com/1689183/63809524-5fa9d400-c8d7-11e9-9641-a770021b12f1.png)

**Comment by ryanctan** [comment]
@epicfaace is this something you can still do?

**Comment by epicfaace** [comment]
This is already there (https://grand-tour-explorer-2017-alpha.herokuapp.com/#/). We just need to install force-ssl-heroku (https://www.npmjs.com/package/force-ssl-heroku) to redirect http to https.
