### ISSUE TITLE
bug in alpha for red negative strike through

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#179]
when you click to red negative strike through in the name search box, the red does not revert to normal after consecutive clicking: it seems to be the case only in this search box, but worthwhile trying for more

<img width="1340" alt="Screen Shot 2019-08-26 at 5 51 03 PM" src="https://user-images.githubusercontent.com/4521013/63789800-eeedc200-c8ac-11e9-9f5f-0f51698ccafb.png">

**Comment by ryanctan** [comment]
Bug exists in beta as well but site doesn't crash (only Internal Server Error and query won't perform)

**Comment by ryanctan** [comment]
Has to do with searchMap in query.js, not recognizing as fullName as array

**Comment by ryanctan** [comment]
Not being an array was incidental... real error was 

MongoError: $not needs a regex or a document

**Comment by ryanctan** [comment]
I think there are cases where either fullName or alternateName turns up null, so it thinks it's not an array because there's only one expression?

**Comment by ryanctan** [comment]
parseQuery packages the $or query, which is an array into a $not query, which is a single object. We instead want to make _each_ of the array elements within $or into a $not query, rather than $not the whole thing.
