### ISSUE TITLE
bug alpha question marks

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#180]
as you explore explore page a question marks remains floating, see pic here, where it seems to eb the one from travel date that has moved up in above search box?
<img width="1441" alt="Screen Shot 2019-08-26 at 5 43 46 PM" src="https://user-images.githubusercontent.com/4521013/63790199-ae427880-c8ad-11e9-9df5-54593232af7b.png">

**Comment by ryanctan** [comment]
Problem arises for filters whose size are not uniform (like dates)
