### ISSUE TITLE
duplicate list total number errros

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#188]
I opened a saved list, it showed to have 50 entries which is correct (Paul); i duplicated it and renamed it (Paul all) and this new list shows 49 total entries which is incorrect (the total is as it should
<img width="1218" alt="Screen Shot 2019-09-06 at 10 00 16 AM" src="https://user-images.githubusercontent.com/4521013/64446641-3256e600-d08e-11e9-9597-d13822ed206f.png">
 be fifty entries)

**Comment by ryanctan** [comment]
May be related to #157

**Comment by ryanctan** [comment]
Can't reproduce
