### ISSUE TITLE
Map visualization

### ISSUE THREAD

**Issue by ryanctan** [cestastanford/grandtour#192]
todo:
- selected locations, similar to Explore feature: perhaps adds outline to dots
- states color legend + selector
- selector look more like Explore
- tooltips look more like minimap
- show selected vs. show alll

**Comment by ceserani** [comment]
states data coming, hopefully tomorrow

**Comment by ceserani** [comment]
here are the color by state keys to start with:
![image](https://user-images.githubusercontent.com/4521013/64810779-de964200-d550-11e9-9ff0-1cb74e981b8b.png)

**Comment by ceserani** [comment]
ryan, this is what i envision:
--the states listed underneath the map
--color key shown (as a large dot?, as a rectangular block?) next to them
--option to either 1)color by that state key the dots already on the map (be these the totality of the dots, or the dots selected by the reader by the selection box) or 2) to put on the map all the dots of locations pertaining to that state
--note that the order of the state names in previous comment reflects their frequency of appearance in the data and should thus be maintained in the appearance of the state names color keys under the map

**Comment by ceserani** [comment]
Ryan, the missing coordinates spreadsheet tab final (https://docs.google.com/spreadsheets/d/1cBPWKer_VWrpAA4ue7gfg_l3HOEJTbe4sKpGjRj_5wQ/edit#gid=1773085202) now contains in its J column the data for 18th-century states relative to our places data. 
Also: we should add this info to the location data in the explorer.
and this spreadsheet should be the basis for the TSV table for DWLD. Will you try to make this table and create the DWLD[icon] in the Explorer where one will be able to get it? The TVS table should be called smthing like Places Data Schema (?i'll keep thinking of a better name) and should contain these columns from the missing coordinates spreadsheet fianl tab: A B C D G H I J K L M (excluding E G N O)
