### ISSUE TITLE
negative red line through gets stuck on sources

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#203]
negative red line through gets stuck on sources, see here:
![image](https://user-images.githubusercontent.com/4521013/65003262-978bb200-d8ac-11e9-9368-3ea07c51364c.png)

**Comment by epicfaace** [comment]
This is an issue (though the screenshot above seems to not display properly). Here's how I reproduced it:
- Open "Sources" in "Explore".
- Click on a single item quickly, multiple times, until you get to the following state:
![image](https://user-images.githubusercontent.com/1689183/65011337-0d514700-d8c8-11e9-8aa2-c066e0476ef9.png)

**Comment by ryanctan** [comment]
Could be related to #179, it appears negative queries aren't working for Sources either

**Comment by ryanctan** [comment]
@epicfaace trying to debug this but can't run `entries_updater_new.py` because I don't have `titles_for_sources_features.csv`, could you attach it here or send it to me? Also, let me know if I should include it in the `python_scripts` directory.

**Comment by epicfaace** [comment]
Sent you an email.

**Comment by ryanctan** [comment]
@epicfaace I think this may have been fixed by one of your recent merges! Can you check on the alpha to confirm, and if so, close this issue?

**Comment by epicfaace** [comment]
It's still there on alpha -- it comes intermittently.
