### ISSUE TITLE
bug in footnotes numbers

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#33]
There seems to be a new bug in footnotes numbering in the narrative parts of the entries: some numbers in the text are transformed into footnotes hyperscript reference numbers. Look at entry 2803, in the third paragraph: where amounts of pounds, prefixed by the symbol for pounds, are so rendered; note that when you click on them you get a box saying 'undefined' (bc of course there is no footnote text to go with them)--see images below

<img width="574" alt="screen shot 2019-02-18 at 4 30 43 pm" src="https://user-images.githubusercontent.com/4521013/52982564-abfddf80-339b-11e9-8fe9-7416668514b2.png">
<img width="376" alt="screen shot 2019-02-18 at 4 35 48 pm" src="https://user-images.githubusercontent.com/4521013/52982574-b61fde00-339b-11e9-8ccc-ff6c304ef68e.png">

**Comment by epicfaace** [comment]
Problems:
It matches the following because unicode has a semicolon:
1. `&#39;14.10`
2. `&#39;36 a year`

Solutions:
- unescape characters first
- manually get rid of case 1 by doing a replace temporarily
