### ISSUE TITLE
bug in search birth/death date

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#36]
When you click on actionable year of birth or death in Search, which should give you as a List all entries of travelers who were born or died in that same year, you get a false no results. Compare here below what happens when, starting from Elizabeth Gibbes entry page (entry 1932), you click on her year of birth of 1761, and you get no results, to when you search in Explore for birth year 1761 and you get 28 results   
![image](https://user-images.githubusercontent.com/4521013/53291455-7759a180-3768-11e9-8c46-705c6ff31345.png)
![image](https://user-images.githubusercontent.com/4521013/53291459-82143680-3768-11e9-8c92-e0f926cfb124.png)

**Comment by epicfaace** [comment]
This must be no longer an issue. When I search "1761", both are showing "28 results" for me.

http://grand-tour-explorer-2017.herokuapp.com/#/search/%7B%22birthDate%22:%7B%22startYear%22:%221761%22,%22endYear%22:%221761%22%7D%7D

http://grand-tour-explorer-2017.herokuapp.com/#/explore/%7B%22birthDate%22:%7B%22startYear%22:%221761%22,%22endYear%22:%221761%22%7D%7D

**Comment by epicfaace** [comment]
Click on the year link -- it does not search by year.

![image](https://user-images.githubusercontent.com/1689183/55996521-6ad3ce80-5c6c-11e9-91db-95f47afd5b90.png)
