### ISSUE TITLE
Rename Explore to Survey - do we rename url too?

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#48]

**Comment by epicfaace** [comment]
I'm thinking "no"

**Comment by epicfaace** [comment]
i.e., http://grand-tour-explorer-2017.herokuapp.com/#/explore/ --> http://grand-tour-explorer-2017.herokuapp.com/#/survey/

**Comment by ceserani** [comment]
no just the tab within the explorer as you did

**Comment by epicfaace** [comment]
Good, thanks
