### ISSUE TITLE
List of fields to group/size/color by

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#52]

**Comment by ryanctan** [comment]
@epicfaace is this issue fixed? If not, what should this look like?

**Comment by epicfaace** [comment]
@ryanctan can we safely close this then?

**Comment by ceserani** [comment]
I think this has to do with dots visualizations
So that yes I would close it here
I

Sent from my iPhone

On Jul 5, 2019, at 3:00 AM, Ashwin Ramaswami <notifications@github.com<mailto:notifications@github.com>> wrote:


@ryanctan<https://github.com/ryanctan> can we safely close this then?
