### ISSUE TITLE
and/or/not

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#55]
for free search: we need to have this option and/or/not for  search terms, meaning that now it woks that you search for a word and than an additional word, while it would be great to be able to search for entries that contain a certain word but not another 

for example that contain 'slave' but not 'persian'

**Comment by epicfaace** [comment]
Let's allow multiple "search" panes to be in the "Survey" tab, with a "NOT" option enabled.

![image](https://user-images.githubusercontent.com/1689183/55289121-15f0a800-5390-11e9-8d55-2417771c069d.png)

**Comment by epicfaace** [comment]
Let's add the "any/all" buttons and add a "NOT" button to "Free search".

![image](https://user-images.githubusercontent.com/1689183/55289138-49cbcd80-5390-11e9-90cf-4f85aa01941a.png)
