### ISSUE TITLE
Consider changing any/all to or/and

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#57]
This is on the Explore tab -- any/all is confusing, let's change it to or/and.

![image](https://user-images.githubusercontent.com/1689183/60151224-c48a6600-9790-11e9-9ec7-b7f8ce45179c.png)

**Comment by epicfaace** [comment]
@ceserani can you confirm that you're ok with this change -- and then Ryan can work on it.

**Comment by ceserani** [comment]
Not yet on this one—wait

Sent from my iPhone

On Jun 26, 2019, at 6:33 AM, Ashwin Ramaswami <notifications@github.com<mailto:notifications@github.com>> wrote:


@ceserani<https://github.com/ceserani> can you confirm that you're ok with this change -- and then Ryan can work on it.

**Comment by ryanctan** [comment]
Closing for now... will open new issue if we want to revert change!
