### ISSUE TITLE
Show footnotes on sidebar

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#69]
Based on #67.

Just like the "mentioned names" section.

Include both in the data augment.

**Comment by epicfaace** [comment]
@ryanctan Code pointer: https://github.com/cestastanford/grandtour/blob/9212cb7bd8b9a4e0bb3cc583375ecbb4bb28768a/public/entry/entry.pug#L268

You can probably just copy what's there for mentioned names and then change it a bit.

**Comment by ryanctan** [comment]
Fixed by #134
