### ISSUE TITLE
Mentioned names -- instead of free search, instead search the name array itself

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#70]

**Comment by ceserani** [comment]
and here is icon to use now, ideally in a softer color, pastel yellow or orange
<img width="392" alt="Screen Shot 2019-04-13 at 12 17 25 PM" src="https://user-images.githubusercontent.com/4521013/56084370-0721e080-5de7-11e9-9b3c-480a352771ac.png">
