### ISSUE TITLE
Renaming / wording changes

### ISSUE THREAD

**Issue by epicfaace** [cestastanford/grandtour#73]
Change “Fullname” to “Traveler Name”
Change “Dimensions” to something?  “Fields”?  “Exploration Fields”?

Change to EMPLOYMENTS AND IDENTIFIERS to INGAMELLS’ Employments & Identifiers
Change travel (in database) to trip

Add short instructions on Explore to show people how to use and find results.
‘make your selection and scroll down to see your results’
Make ‘your filters’ and ‘matching results’ language consistent
In the entries that didn’t exist in the dictionary and were created from another one, replace the text “From Doe, John” to “From the entry of John Doe” for clarity.
Think about changing “See…” in Fullnames Explore facet to something else (“also known as”, “alternate name of”)

**Comment by ceserani** [comment]
![image](https://user-images.githubusercontent.com/4521013/58288634-0e82c500-7d69-11e9-8031-edea3b443949.png)

**Comment by ceserani** [comment]
update and complete: Aswhin, can you read or too small:
![image](https://user-images.githubusercontent.com/4521013/58513613-ac550600-8154-11e9-8758-513e6f798631.png)
