### ISSUE TITLE
error in appearance of fields

### ISSUE THREAD

**Issue by ceserani** [cestastanford/grandtour#92]
even when empty, because erroneous data was deleted, the field ‘parents’ appears in various entries—see example below;
fields that are empty should not appear

**Comment by epicfaace** [comment]
Can you put a screenshot / link to the example?

**Comment by epicfaace** [comment]
@ceserani

**Comment by ceserani** [comment]
https://academic-oup-com.stanford.idm.oclc.org/jhc/issue/19/2

you see here Parents appearing even if filed is empty: this is entry 23.1; there are other instances (all in newly created entries, bc that is where it happens that one deletes the names of the parents)

**Comment by ceserani** [comment]
here correct screenshot, earlier it was a mistake:
<img width="1009" alt="Screen Shot 2019-05-08 at 9 31 12 PM" src="https://user-images.githubusercontent.com/4521013/57427526-20952d00-71d9-11e9-83cc-266c96fa66ee.png">

**Comment by epicfaace** [comment]
@ryanctan can you look into this and see if it's still an issue?

**Comment by ryanctan** [comment]
@epicfaace the glitch only seems to happen with the new entries, is it possible that it has to do with the data itself? or whatever was used to parse the original entries?

**Comment by epicfaace** [comment]
Not sure, will need to investigate further.

**Comment by ryanctan** [comment]
@epicfaace any updates?
